// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

# The speech generation config.
public type SpeechConfig record {
    # The configuration in case of single-voice output.
    VoiceConfig voiceConfig?;
    # Optional. The configuration for the multi-speaker setup.
    #  It is mutually exclusive with the voice_config field.
    MultiSpeakerVoiceConfig multiSpeakerVoiceConfig?;
    # Optional. Language code (in BCP 47 format, e.g. "en-US") for speech
    #  synthesis.
    # 
    #  Valid values are: de-DE, en-AU, en-GB, en-IN, en-US, es-US, fr-FR, hi-IN,
    #  pt-BR, ar-XA, es-ES, fr-CA, id-ID, it-IT, ja-JP, tr-TR, vi-VN, bn-IN,
    #  gu-IN, kn-IN, ml-IN, mr-IN, ta-IN, te-IN, nl-NL, ko-KR, cmn-CN, pl-PL,
    #  ru-RU, and th-TH.
    string languageCode?;
};

# Metadata returned to client when grounding is enabled.
public type GroundingMetadata record {
    # Optional. Google search entry for the following-up web searches.
    SearchEntryPoint searchEntryPoint?;
    # List of supporting references retrieved from specified grounding source.
    GroundingChunk[] groundingChunks?;
    # List of grounding support.
    GroundingSupport[] groundingSupports?;
    # Metadata related to retrieval in the grounding flow.
    RetrievalMetadata retrievalMetadata?;
    # Web search queries for the following-up web search.
    string[] webSearchQueries?;
};

# The `Schema` object allows the definition of input and output data types.
#  These types can be objects, but also primitives and arrays.
#  Represents a select subset of an [OpenAPI 3.0 schema
#  object](https://spec.openapis.org/oas/v3.0.3#schema).
public type Schema record {
    # Required. Data type.
    int 'type;
    # Optional. The format of the data. This is used only for primitive
    #  datatypes. Supported formats:
    #   for NUMBER type: float, double
    #   for INTEGER type: int32, int64
    #   for STRING type: enum, date-time
    string format?;
    # Optional. The title of the schema.
    string title?;
    # Optional. A brief description of the parameter. This could contain examples
    #  of use. Parameter description may be formatted as Markdown.
    string description?;
    # Optional. Indicates if the value may be null.
    boolean nullable?;
    # Optional. Possible values of the element of Type.STRING with enum format.
    #  For example we can define an Enum Direction as :
    #  {type:STRING, format:enum, enum:["EAST", NORTH", "SOUTH", "WEST"]}
    string[] 'enum?;
    # Optional. Schema of the elements of Type.ARRAY.
    Schema items?;
    # Optional. Maximum number of the elements for Type.ARRAY.
    string maxItems?;
    # Optional. Minimum number of the elements for Type.ARRAY.
    string minItems?;
    # Optional. Properties of Type.OBJECT.
    record {|Schema...;|} properties?;
    # Optional. Required properties of Type.OBJECT.
    string[] required?;
    # Optional. Minimum number of the properties for Type.OBJECT.
    string minProperties?;
    # Optional. Maximum number of the properties for Type.OBJECT.
    string maxProperties?;
    # Optional. SCHEMA FIELDS FOR TYPE INTEGER and NUMBER
    #  Minimum value of the Type.INTEGER and Type.NUMBER
    decimal minimum?;
    # Optional. Maximum value of the Type.INTEGER and Type.NUMBER
    decimal maximum?;
    # Optional. SCHEMA FIELDS FOR TYPE STRING
    #  Minimum length of the Type.STRING
    string minLength?;
    # Optional. Maximum length of the Type.STRING
    string maxLength?;
    # Optional. Pattern of the Type.STRING to restrict a string to a regular
    #  expression.
    string pattern?;
    # Optional. Example of the object. Will only populated when the object is the
    #  root.
    GoogleProtobufValue example?;
    # Optional. The value should be validated against any (one or more) of the
    #  subschemas in the list.
    Schema[] anyOf?;
    # Optional. The order of the properties.
    #  Not a standard field in open api spec. Used to determine the order of the
    #  properties in the response.
    string[] propertyOrdering?;
    # Optional. Default value of the field. Per JSON Schema, this field is
    #  intended for documentation generators and doesn't affect validation. Thus
    #  it's included here and ignored so that developers who send schemas with a
    #  `default` field don't get unknown-field errors.
    GoogleProtobufValue default?;
};

# Tool that executes code generated by the model, and automatically returns
#  the result to the model.
# 
#  See also `ExecutableCode` and `CodeExecutionResult` which are only generated
#  when using this tool.
public type CodeExecution record {
};

# Response from the model supporting multiple candidate responses.
# 
#  Safety ratings and content filtering are reported for both
#  prompt in `GenerateContentResponse.prompt_feedback` and for each candidate
#  in `finish_reason` and in `safety_ratings`. The API:
#   - Returns either all requested candidates or none of them
#   - Returns no candidates at all only if there was something wrong with the
#     prompt (check `prompt_feedback`)
#   - Reports feedback on each candidate in `finish_reason` and
#     `safety_ratings`.
public type GenerateContentResponse record {
    # Candidate responses from the model.
    Candidate[] candidates;
    # Returns the prompt's feedback related to the content filters.
    GenerateContentResponse_PromptFeedback promptFeedback?;
    # Output only. Metadata on the generation requests' token usage.
    GenerateContentResponse_UsageMetadata usageMetadata?;
    # Output only. The model version used to generate the response.
    string modelVersion?;
    # Output only. response_id is used to identify each response.
    string responseId?;
};

# Batch request to get embeddings from the model for a list of prompts.
public type BatchEmbedContentsRequest record {
    # Required. The model's resource name. This serves as an ID for the Model to
    #  use.
    # 
    #  This name should match a model name returned by the `ListModels` method.
    # 
    #  Format: `models/{model}`
    string model;
    # Required. Embed requests for the batch. The model in each of these requests
    #  must match the model specified `BatchEmbedContentsRequest.model`.
    EmbedContentRequest[] requests;
};

# Attribution for a source that contributed to an answer.
public type GroundingAttribution record {
    # Output only. Identifier for the source contributing to this attribution.
    AttributionSourceId sourceId?;
    # Grounding source content that makes up this attribution.
    Content content?;
};

# Context of the a single url retrieval.
public type UrlMetadata record {
    # Retrieved url by the tool.
    string retrievedUrl?;
    # Status of the url retrieval.
    int urlRetrievalStatus?;
};

# Counts the number of tokens in the `prompt` sent to a model.
# 
#  Models may tokenize text differently, so each model may return a different
#  `token_count`.
public type CountTokensRequest record {
    # Required. The model's resource name. This serves as an ID for the Model to
    #  use.
    # 
    #  This name should match a model name returned by the `ListModels` method.
    # 
    #  Format: `models/{model}`
    string model;
    # Optional. The input given to the model as a prompt. This field is ignored
    #  when `generate_content_request` is set.
    Content[] contents?;
    # Optional. The overall input given to the `Model`. This includes the prompt
    #  as well as other model steering information like [system
    #  instructions](https://ai.google.dev/gemini-api/docs/system-instructions),
    #  and/or function declarations for [function
    #  calling](https://ai.google.dev/gemini-api/docs/function-calling).
    #  `Model`s/`Content`s and `generate_content_request`s are mutually
    #  exclusive. You can either send `Model` + `Content`s or a
    #  `generate_content_request`, but never both.
    GenerateContentRequest generateContentRequest?;
};

# Configuration for retrieving grounding content from a `Corpus` or
#  `Document` created using the Semantic Retriever API.
public type SemanticRetrieverConfig record {
    # Required. Name of the resource for retrieval. Example: `corpora/123` or
    #  `corpora/123/documents/abc`.
    string 'source;
    # Required. Query to use for matching `Chunk`s in the given resource by
    #  similarity.
    Content query;
    # Optional. Filters for selecting `Document`s and/or `Chunk`s from the
    #  resource.
    MetadataFilter[] metadataFilters?;
    # Optional. Maximum number of relevant `Chunk`s to retrieve.
    int:Signed32 maxChunksCount?;
    # Optional. Minimum relevance score for retrieved relevant `Chunk`s.
    float minimumRelevanceScore?;
};

# Safety setting, affecting the safety-blocking behavior.
# 
#  Passing a safety setting for a category changes the allowed probability that
#  content is blocked.
public type SafetySetting record {
    # Required. The category for this setting.
    int category;
    # Required. Controls the probability threshold at which harm is blocked.
    int threshold;
};

# Google search entry point.
public type SearchEntryPoint record {
    # Optional. Web content snippet that can be embedded in a web page or an app
    #  webview.
    string renderedContent?;
    # Optional. Base64 encoded JSON representing array of <search term, search
    #  url> tuple.
    string sdkBlob?;
};

# Identifier for a `Chunk` retrieved via Semantic Retriever specified in the
#  `GenerateAnswerRequest` using `SemanticRetrieverConfig`.
public type AttributionSourceId_SemanticRetrieverChunk record {
    # Output only. Name of the source matching the request's
    #  `SemanticRetrieverConfig.source`. Example: `corpora/123` or
    #  `corpora/123/documents/abc`
    string 'source?;
    # Output only. Name of the `Chunk` containing the attributed text.
    #  Example: `corpora/123/documents/abc/chunks/xyz`
    string chunk?;
};

# Identifier for the source contributing to this attribution.
public type AttributionSourceId record {
    # Identifier for an inline passage.
    AttributionSourceId_GroundingPassageId groundingPassage?;
    # Identifier for a `Chunk` fetched via Semantic Retriever.
    AttributionSourceId_SemanticRetrieverChunk semanticRetrieverChunk?;
};

# Metadata related to url context retrieval tool.
public type UrlContextMetadata record {
    # List of url context.
    UrlMetadata[] urlMetadata?;
};

# URI based data.
public type FileData record {
    # Optional. The IANA standard MIME type of the source data.
    string mimeType?;
    # Required. URI.
    string fileUri;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Tool details that the model may use to generate response.
# 
#  A `Tool` is a piece of code that enables the system to interact with
#  external systems to perform an action, or set of actions, outside of
#  knowledge and scope of the model.
public type Tool record {
    # Optional. A list of `FunctionDeclarations` available to the model that can
    #  be used for function calling.
    # 
    #  The model or system does not execute the function. Instead the defined
    #  function may be returned as a
    #  [FunctionCall][google.ai.generativelanguage.v1beta.Part.function_call] with
    #  arguments to the client side for execution. The model may decide to call a
    #  subset of these functions by populating
    #  [FunctionCall][google.ai.generativelanguage.v1beta.Part.function_call] in
    #  the response. The next conversation turn may contain a
    #  [FunctionResponse][google.ai.generativelanguage.v1beta.Part.function_response]
    #  with the [Content.role][google.ai.generativelanguage.v1beta.Content.role]
    #  "function" generation context for the next model turn.
    FunctionDeclaration[] functionDeclarations?;
    # Optional. Retrieval tool that is powered by Google search.
    GoogleSearchRetrieval googleSearchRetrieval?;
    # Optional. Enables the model to execute code as part of generation.
    CodeExecution codeExecution?;
    # Optional. GoogleSearch tool type.
    #  Tool to support Google Search in Model. Powered by Google.
    Tool_GoogleSearch googleSearch?;
    # Optional. Tool to support URL context retrieval.
    UrlContext urlContext?;
};

# A response candidate generated from the model.
public type Candidate record {
    # Output only. Index of the candidate in the list of response candidates.
    int:Signed32 index?;
    # Output only. Generated content returned from the model.
    Content content;
    # Optional. Output only. The reason why the model stopped generating tokens.
    # 
    #  If empty, the model has not stopped generating tokens.
    int|string finishReason?;
    # List of ratings for the safety of a response candidate.
    # 
    #  There is at most one rating per category.
    SafetyRating[] safetyRatings?;
    # Output only. Citation information for model-generated candidate.
    # 
    #  This field may be populated with recitation information for any text
    #  included in the `content`. These are passages that are "recited" from
    #  copyrighted material in the foundational LLM's training data.
    CitationMetadata citationMetadata?;
    # Output only. Token count for this candidate.
    int:Signed32 tokenCount?;
    # Output only. Attribution information for sources that contributed to a
    #  grounded answer.
    # 
    #  This field is populated for `GenerateAnswer` calls.
    GroundingAttribution[] groundingAttributions?;
    # Output only. Grounding metadata for the candidate.
    # 
    #  This field is populated for `GenerateContent` calls.
    GroundingMetadata groundingMetadata?;
    # Output only. Average log probability score of the candidate.
    decimal avgLogprobs?;
    # Output only. Log-likelihood scores for the response tokens and top tokens
    LogprobsResult logprobsResult?;
    # Output only. Metadata related to url context retrieval tool.
    UrlContextMetadata urlContextMetadata?;
};

# Raw media bytes.
# 
#  Text should not be sent as raw bytes, use the 'text' field.
public type Blob record {
    # The IANA standard MIME type of the source data.
    #  Examples:
    #    - image/png
    #    - image/jpeg
    #  If an unsupported MIME type is provided, an error will be returned. For a
    #  complete list of supported types, see [Supported file
    #  formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).
    string mimeType?;
    # Raw bytes for media formats.
    string data?;
};

# Feedback related to the input data used to answer the question, as opposed
#  to the model-generated response to the question.
public type GenerateAnswerResponse_InputFeedback record {
    # Optional. If set, the input was blocked and no candidates are returned.
    #  Rephrase the input.
    int blockReason?;
    # Ratings for safety of the input.
    #  There is at most one rating per category.
    SafetyRating[] safetyRatings?;
};

# The response to an `EmbedContentRequest`.
public type EmbedContentResponse record {
    # Output only. The embedding generated from the input content.
    ContentEmbedding embedding;
};

# Represents token counting info for a single modality.
public type ModalityTokenCount record {
    # The modality associated with this token count.
    int|string modality?;
    # Number of tokens.
    int:Signed32 tokenCount?;
};

# Tool to support URL context retrieval.
public type UrlContext record {
};

# The configuration for a single speaker in a multi speaker setup.
public type SpeakerVoiceConfig record {
    # Required. The name of the speaker to use. Should be the same as in the
    #  prompt.
    string speaker;
    # Required. The configuration for the voice to use.
    VoiceConfig voiceConfig;
};

# A collection of source attributions for a piece of content.
public type CitationMetadata record {
    # Citations to sources for a specific response.
    CitationSource[] citationSources?;
};

# Represents a dynamically typed value which can be either null, a number, a string, a boolean, a recursive struct value, or a list of values.
public type GoogleProtobufValue anydata;

# Logprobs Result
public type LogprobsResult record {
    # Length = total number of decoding steps.
    LogprobsResult_TopCandidates[] topCandidates?;
    # Length = total number of decoding steps.
    #  The chosen candidates may or may not be in top_candidates.
    LogprobsResult_Candidate[] chosenCandidates?;
};

# A datatype containing media that is part of a multi-part `Content` message.
# 
#  A `Part` consists of data which has an associated datatype. A `Part` can only
#  contain one of the accepted types in `Part.data`.
# 
#  A `Part` must have a fixed IANA MIME type identifying the type and subtype
#  of the media if the `inline_data` field is filled with raw bytes.
public type Part record {
    # Inline text.
    string text;
    # Inline media bytes.
    Blob inlineData?;
    # A predicted `FunctionCall` returned from the model that contains
    #  a string representing the `FunctionDeclaration.name` with the
    #  arguments and their values.
    FunctionCall functionCall?;
    # The result output of a `FunctionCall` that contains a string
    #  representing the `FunctionDeclaration.name` and a structured JSON
    #  object containing any output from the function is used as context to
    #  the model.
    FunctionResponse functionResponse?;
    # URI based data.
    FileData fileData?;
    # Code generated by the model that is meant to be executed.
    ExecutableCode executableCode?;
    # Result of executing the `ExecutableCode`.
    CodeExecutionResult codeExecutionResult?;
    # Optional. Video metadata. The metadata should only be specified while the
    #  video data is presented in inline_data or file_data.
    VideoMetadata videoMetadata?;
    # Optional. Indicates if the part is thought from the model.
    boolean thought?;
    # Optional. An opaque signature for the thought so it can be reused in
    #  subsequent requests.
    string thoughtSignature?;
};

# The base structured datatype containing multi-part content of a message.
# 
#  A `Content` includes a `role` field designating the producer of the `Content`
#  and a `parts` field containing multi-part data that contains the content of
#  the message turn.
public type Content record {
    # Ordered `Parts` that constitute a single message. Parts may have different
    #  MIME types.
    Part[] parts;
    # Optional. The producer of the content. Must be either 'user' or 'model'.
    # 
    #  Useful to set for multi-turn conversations, otherwise can be left blank
    #  or unset.
    string role?;
};

# The Tool configuration containing parameters for specifying `Tool` use
#  in the request.
public type ToolConfig record {
    # Optional. Function calling config.
    FunctionCallingConfig functionCallingConfig?;
};

# Request to generate a completion from the model.
public type GenerateContentRequest record {
    # Required. The name of the `Model` to use for generating the completion.
    # 
    #  Format: `models/{model}`.
    string model;
    # Optional. Developer set [system
    #  instruction(s)](https://ai.google.dev/gemini-api/docs/system-instructions).
    #  Currently, text only.
    Content systemInstruction?;
    # Required. The content of the current conversation with the model.
    # 
    #  For single-turn queries, this is a single instance. For multi-turn queries
    #  like [chat](https://ai.google.dev/gemini-api/docs/text-generation#chat),
    #  this is a repeated field that contains the conversation history and the
    #  latest request.
    Content[] contents;
    # Optional. A list of `Tools` the `Model` may use to generate the next
    #  response.
    # 
    #  A `Tool` is a piece of code that enables the system to interact with
    #  external systems to perform an action, or set of actions, outside of
    #  knowledge and scope of the `Model`. Supported `Tool`s are `Function` and
    #  `code_execution`. Refer to the [Function
    #  calling](https://ai.google.dev/gemini-api/docs/function-calling) and the
    #  [Code execution](https://ai.google.dev/gemini-api/docs/code-execution)
    #  guides to learn more.
    Tool[] tools?;
    # Optional. Tool configuration for any `Tool` specified in the request. Refer
    #  to the [Function calling
    #  guide](https://ai.google.dev/gemini-api/docs/function-calling#function_calling_mode)
    #  for a usage example.
    ToolConfig toolConfig?;
    # Optional. A list of unique `SafetySetting` instances for blocking unsafe
    #  content.
    # 
    #  This will be enforced on the `GenerateContentRequest.contents` and
    #  `GenerateContentResponse.candidates`. There should not be more than one
    #  setting for each `SafetyCategory` type. The API will block any contents and
    #  responses that fail to meet the thresholds set by these settings. This list
    #  overrides the default settings for each `SafetyCategory` specified in the
    #  safety_settings. If there is no `SafetySetting` for a given
    #  `SafetyCategory` provided in the list, the API will use the default safety
    #  setting for that category. Harm categories HARM_CATEGORY_HATE_SPEECH,
    #  HARM_CATEGORY_SEXUALLY_EXPLICIT, HARM_CATEGORY_DANGEROUS_CONTENT,
    #  HARM_CATEGORY_HARASSMENT, HARM_CATEGORY_CIVIC_INTEGRITY are supported.
    #  Refer to the [guide](https://ai.google.dev/gemini-api/docs/safety-settings)
    #  for detailed information on available safety settings. Also refer to the
    #  [Safety guidance](https://ai.google.dev/gemini-api/docs/safety-guidance) to
    #  learn how to incorporate safety considerations in your AI applications.
    SafetySetting[] safetySettings?;
    # Optional. Configuration options for model generation and outputs.
    GenerationConfig generationConfig?;
    # Optional. The name of the content
    #  [cached](https://ai.google.dev/gemini-api/docs/caching) to use as context
    #  to serve the prediction. Format: `cachedContents/{cachedContent}`
    string cachedContent?;
};

# A set of the feedback metadata the prompt specified in
#  `GenerateContentRequest.content`.
public type GenerateContentResponse_PromptFeedback record {
    # Optional. If set, the prompt was blocked and no candidates are returned.
    #  Rephrase the prompt.
    int blockReason?;
    # Ratings for safety of the prompt.
    #  There is at most one rating per category.
    SafetyRating[] safetyRatings?;
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    # Gemini API Key
    @display {label: "", kind: "password"}
    string xGoogApiKey;
|};

# Describes the options to customize dynamic retrieval.
public type DynamicRetrievalConfig record {
    # The mode of the predictor to be used in dynamic retrieval.
    int mode?;
    # The threshold to be used in dynamic retrieval.
    #  If not set, a system default value is used.
    float dynamicThreshold?;
};

# Represents a time interval, encoded as a Timestamp start (inclusive) and a
#  Timestamp end (exclusive).
# 
#  The start must be less than or equal to the end.
#  When the start equals the end, the interval is empty (matches no time).
#  When both start and end are unspecified, the interval matches any time.
public type Interval record {
    # Optional. Inclusive start of the interval.
    # 
    #  If specified, a Timestamp matching this interval will have to be the same
    #  or after the start.
    string startTime?;
    # Optional. Exclusive end of the interval.
    # 
    #  If specified, a Timestamp matching this interval will have to be before the
    #  end.
    string endTime?;
};

# The configuration for the voice to use.
public type VoiceConfig record {
    # The configuration for the prebuilt voice to use.
    PrebuiltVoiceConfig prebuiltVoiceConfig?;
};

# The response to a `BatchEmbedContentsRequest`.
public type BatchEmbedContentsResponse record {
    # Output only. The embeddings for each request, in the same order as provided
    #  in the batch request.
    ContentEmbedding[] embeddings?;
};

# A response from `CountTokens`.
# 
#  It returns the model's `token_count` for the `prompt`.
public type CountTokensResponse record {
    # The number of tokens that the `Model` tokenizes the `prompt` into. Always
    #  non-negative.
    int:Signed32 totalTokens?;
    # Number of tokens in the cached part of the prompt (the cached content).
    int:Signed32 cachedContentTokenCount?;
    # Output only. List of modalities that were processed in the request input.
    ModalityTokenCount[] promptTokensDetails?;
    # Output only. List of modalities that were processed in the cached content.
    ModalityTokenCount[] cacheTokensDetails?;
};

# Code generated by the model that is meant to be executed, and the result
#  returned to the model.
# 
#  Only generated when using the `CodeExecution` tool, in which the code will
#  be automatically executed, and a corresponding `CodeExecutionResult` will
#  also be generated.
public type ExecutableCode record {
    # Required. Programming language of the `code`.
    int language;
    # Required. The code to be executed.
    string code;
};

# A citation to a source for a portion of a specific response.
public type CitationSource record {
    # Optional. Start of segment of the response that is attributed to this
    #  source.
    # 
    #  Index indicates the start of the segment, measured in bytes.
    int:Signed32 startIndex?;
    # Optional. End of the attributed segment, exclusive.
    int:Signed32 endIndex?;
    # Optional. URI that is attributed as a source for a portion of the text.
    string uri?;
    # Optional. License for the GitHub project that is attributed as a source for
    #  segment.
    # 
    #  License info is required for code citations.
    string license?;
};

# Grounding chunk.
public type GroundingChunk record {
    # Grounding chunk from the web.
    GroundingChunk_Web web?;
};

# Metadata describes the input video content.
public type VideoMetadata record {
    # Optional. The start offset of the video.
    @constraint:String {pattern: re `^-?(?:0|[1-9][0-9]{0,11})(?:\.[0-9]{1,9})?s$`}
    string startOffset?;
    # Optional. The end offset of the video.
    @constraint:String {pattern: re `^-?(?:0|[1-9][0-9]{0,11})(?:\.[0-9]{1,9})?s$`}
    string endOffset?;
    # Optional. The frame rate of the video sent to the model. If not specified,
    #  the default value will be 1.0. The fps range is (0.0, 24.0].
    decimal fps?;
};

# Configuration options for model generation and outputs. Not all parameters
#  are configurable for every model.
public type GenerationConfig record {
    # Optional. Number of generated responses to return. If unset, this will
    #  default to 1. Please note that this doesn't work for previous generation
    #  models (Gemini 1.0 family)
    int:Signed32 candidateCount?;
    # Optional. The set of character sequences (up to 5) that will stop output
    #  generation. If specified, the API will stop at the first appearance of a
    #  `stop_sequence`. The stop sequence will not be included as part of the
    #  response.
    string[] stopSequences?;
    # Optional. The maximum number of tokens to include in a response candidate.
    # 
    #  Note: The default value varies by model, see the `Model.output_token_limit`
    #  attribute of the `Model` returned from the `getModel` function.
    int:Signed32 maxOutputTokens?;
    # Optional. Controls the randomness of the output.
    # 
    #  Note: The default value varies by model, see the `Model.temperature`
    #  attribute of the `Model` returned from the `getModel` function.
    # 
    #  Values can range from [0.0, 2.0].
    float temperature?;
    # Optional. The maximum cumulative probability of tokens to consider when
    #  sampling.
    # 
    #  The model uses combined Top-k and Top-p (nucleus) sampling.
    # 
    #  Tokens are sorted based on their assigned probabilities so that only the
    #  most likely tokens are considered. Top-k sampling directly limits the
    #  maximum number of tokens to consider, while Nucleus sampling limits the
    #  number of tokens based on the cumulative probability.
    # 
    #  Note: The default value varies by `Model` and is specified by
    #  the`Model.top_p` attribute returned from the `getModel` function. An empty
    #  `top_k` attribute indicates that the model doesn't apply top-k sampling
    #  and doesn't allow setting `top_k` on requests.
    float topP?;
    # Optional. The maximum number of tokens to consider when sampling.
    # 
    #  Gemini models use Top-p (nucleus) sampling or a combination of Top-k and
    #  nucleus sampling. Top-k sampling considers the set of `top_k` most probable
    #  tokens. Models running with nucleus sampling don't allow top_k setting.
    # 
    #  Note: The default value varies by `Model` and is specified by
    #  the`Model.top_p` attribute returned from the `getModel` function. An empty
    #  `top_k` attribute indicates that the model doesn't apply top-k sampling
    #  and doesn't allow setting `top_k` on requests.
    int:Signed32 topK?;
    # Optional. Seed used in decoding. If not set, the request uses a randomly
    #  generated seed.
    int:Signed32 seed?;
    # Optional. MIME type of the generated candidate text.
    #  Supported MIME types are:
    #  `text/plain`: (default) Text output.
    #  `application/json`: JSON response in the response candidates.
    #  `text/x.enum`: ENUM as a string response in the response candidates.
    #  Refer to the
    #  [docs](https://ai.google.dev/gemini-api/docs/prompting_with_media#plain_text_formats)
    #  for a list of all supported text MIME types.
    string responseMimeType?;
    # Optional. Output schema of the generated candidate text. Schemas must be a
    #  subset of the [OpenAPI schema](https://spec.openapis.org/oas/v3.0.3#schema)
    #  and can be objects, primitives or arrays.
    # 
    #  If set, a compatible `response_mime_type` must also be set.
    #  Compatible MIME types:
    #  `application/json`: Schema for JSON response.
    #  Refer to the [JSON text generation
    #  guide](https://ai.google.dev/gemini-api/docs/json-mode) for more details.
    Schema responseSchema?;
    # Optional. Output schema of the generated response. This is an alternative
    #  to `response_schema` that accepts [JSON Schema](https://json-schema.org/).
    # 
    #  If set, `response_schema` must be omitted, but `response_mime_type` is
    #  required.
    # 
    #  While the full JSON Schema may be sent, not all features are supported.
    #  Specifically, only the following properties are supported:
    # 
    #  - `$id`
    #  - `$defs`
    #  - `$ref`
    #  - `$anchor`
    #  - `type`
    #  - `format`
    #  - `title`
    #  - `description`
    #  - `enum` (for strings and numbers)
    #  - `items`
    #  - `prefixItems`
    #  - `minItems`
    #  - `maxItems`
    #  - `minimum`
    #  - `maximum`
    #  - `anyOf`
    #  - `oneOf` (interpreted the same as `anyOf`)
    #  - `properties`
    #  - `additionalProperties`
    #  - `required`
    # 
    #  The non-standard `propertyOrdering` property may also be set.
    # 
    #  Cyclic references are unrolled to a limited degree and, as such, may only
    #  be used within non-required properties. (Nullable properties are not
    #  sufficient.) If `$ref` is set on a sub-schema, no other properties, except
    #  for than those starting as a `$`, may be set.
    GoogleProtobufValue responseJsonSchema?;
    # Optional. Presence penalty applied to the next token's logprobs if the
    #  token has already been seen in the response.
    # 
    #  This penalty is binary on/off and not dependant on the number of times the
    #  token is used (after the first). Use
    #  [frequency_penalty][google.ai.generativelanguage.v1beta.GenerationConfig.frequency_penalty]
    #  for a penalty that increases with each use.
    # 
    #  A positive penalty will discourage the use of tokens that have already
    #  been used in the response, increasing the vocabulary.
    # 
    #  A negative penalty will encourage the use of tokens that have already been
    #  used in the response, decreasing the vocabulary.
    float presencePenalty?;
    # Optional. Frequency penalty applied to the next token's logprobs,
    #  multiplied by the number of times each token has been seen in the respponse
    #  so far.
    # 
    #  A positive penalty will discourage the use of tokens that have already
    #  been used, proportional to the number of times the token has been used:
    #  The more a token is used, the more difficult it is for the model to use
    #  that token again increasing the vocabulary of responses.
    # 
    #  Caution: A _negative_ penalty will encourage the model to reuse tokens
    #  proportional to the number of times the token has been used. Small
    #  negative values will reduce the vocabulary of a response. Larger negative
    #  values will cause the model to start repeating a common token  until it
    #  hits the
    #  [max_output_tokens][google.ai.generativelanguage.v1beta.GenerationConfig.max_output_tokens]
    #  limit.
    float frequencyPenalty?;
    # Optional. If true, export the logprobs results in response.
    boolean responseLogprobs?;
    # Optional. Only valid if
    #  [response_logprobs=True][google.ai.generativelanguage.v1beta.GenerationConfig.response_logprobs].
    #  This sets the number of top logprobs to return at each decoding step in the
    #  [Candidate.logprobs_result][google.ai.generativelanguage.v1beta.Candidate.logprobs_result].
    int:Signed32 logprobs?;
    # Optional. Enables enhanced civic answers. It may not be available for all
    #  models.
    boolean enableEnhancedCivicAnswers?;
    # Optional. The requested modalities of the response. Represents the set of
    #  modalities that the model can return, and should be expected in the
    #  response. This is an exact match to the modalities of the response.
    # 
    #  A model may have multiple combinations of supported modalities. If the
    #  requested modalities do not match any of the supported combinations, an
    #  error will be returned.
    # 
    #  An empty list is equivalent to requesting only text.
    int[] responseModalities?;
    # Optional. The speech generation config.
    SpeechConfig speechConfig?;
    # Optional. Config for thinking features.
    #  An error will be returned if this field is set for models that don't
    #  support thinking.
    ThinkingConfig thinkingConfig?;
    # Optional. If specified, the media resolution specified will be used.
    int mediaResolution?;
};

# Segment of the content.
public type Segment record {
    # Output only. The index of a Part object within its parent Content object.
    int:Signed32 partIndex?;
    # Output only. Start index in the given Part, measured in bytes. Offset from
    #  the start of the Part, inclusive, starting at zero.
    int:Signed32 startIndex?;
    # Output only. End index in the given Part, measured in bytes. Offset from
    #  the start of the Part, exclusive, starting at zero.
    int:Signed32 endIndex?;
    # Output only. The text corresponding to the segment from the response.
    string text?;
};

# Identifier for a part within a `GroundingPassage`.
public type AttributionSourceId_GroundingPassageId record {
    # Output only. ID of the passage matching the `GenerateAnswerRequest`'s
    #  `GroundingPassage.id`.
    string passageId?;
    # Output only. Index of the part within the `GenerateAnswerRequest`'s
    #  `GroundingPassage.content`.
    int:Signed32 partIndex?;
};

# Structured representation of a function declaration as defined by the
#  [OpenAPI 3.03 specification](https://spec.openapis.org/oas/v3.0.3). Included
#  in this declaration are the function name and parameters. This
#  FunctionDeclaration is a representation of a block of code that can be used
#  as a `Tool` by the model and executed by the client.
public type FunctionDeclaration record {
    # Required. The name of the function.
    #  Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum
    #  length of 63.
    string name;
    # Required. A brief description of the function.
    string description;
    # Optional. Describes the parameters to this function. Reflects the Open
    #  API 3.03 Parameter Object string Key: the name of the parameter. Parameter
    #  names are case sensitive. Schema Value: the Schema defining the type used
    #  for the parameter.
    Schema parameters?;
    # Optional. Describes the parameters to the function in JSON Schema format.
    #  The schema must describe an object where the properties are the parameters
    #  to the function. For example:
    # 
    #  ```
    #  {
    #    "type": "object",
    #    "properties": {
    #      "name": { "type": "string" },
    #      "age": { "type": "integer" }
    #    },
    #    "additionalProperties": false,
    #    "required": ["name", "age"],
    #    "propertyOrdering": ["name", "age"]
    #  }
    #  ```
    # 
    #  This field is mutually exclusive with `parameters`.
    GoogleProtobufValue parametersJsonSchema?;
    # Optional. Describes the output from this function in JSON Schema format.
    #  Reflects the Open API 3.03 Response Object. The Schema defines the type
    #  used for the response value of the function.
    Schema response?;
    # Optional. Describes the output from this function in JSON Schema format.
    #  The value specified by the schema is the response value of the function.
    # 
    #  This field is mutually exclusive with `response`.
    GoogleProtobufValue responseJsonSchema?;
    # Optional. Specifies the function Behavior.
    #  Currently only supported by the BidiGenerateContent method.
    int behavior?;
};

# Metadata on the generation request's token usage.
public type GenerateContentResponse_UsageMetadata record {
    # Number of tokens in the prompt. When `cached_content` is set, this is
    #  still the total effective prompt size meaning this includes the number of
    #  tokens in the cached content.
    int:Signed32 promptTokenCount?;
    # Number of tokens in the cached part of the prompt (the cached content)
    int:Signed32 cachedContentTokenCount?;
    # Total number of tokens across all the generated response candidates.
    int:Signed32 candidatesTokenCount?;
    # Output only. Number of tokens present in tool-use prompt(s).
    int:Signed32 toolUsePromptTokenCount?;
    # Output only. Number of tokens of thoughts for thinking models.
    int:Signed32 thoughtsTokenCount?;
    # Total token count for the generation request (prompt + response
    #  candidates).
    int:Signed32 totalTokenCount?;
    # Output only. List of modalities that were processed in the request input.
    ModalityTokenCount[] promptTokensDetails?;
    # Output only. List of modalities of the cached content in the request
    #  input.
    ModalityTokenCount[] cacheTokensDetails?;
    # Output only. List of modalities that were returned in the response.
    ModalityTokenCount[] candidatesTokensDetails?;
    # Output only. List of modalities that were processed for tool-use request
    #  inputs.
    ModalityTokenCount[] toolUsePromptTokensDetails?;
};

# Candidate for the logprobs token and score.
public type LogprobsResult_Candidate record {
    # The candidate’s token string value.
    string token?;
    # The candidate’s token id value.
    int:Signed32 tokenId?;
    # The candidate's log probability.
    float logProbability?;
};

# Result of executing the `ExecutableCode`.
# 
#  Only generated when using the `CodeExecution`, and always follows a `part`
#  containing the `ExecutableCode`.
public type CodeExecutionResult record {
    # Required. Outcome of the code execution.
    int outcome;
    # Optional. Contains stdout when code execution is successful, stderr or
    #  other description otherwise.
    string output?;
};

# The configuration for the prebuilt speaker to use.
public type PrebuiltVoiceConfig record {
    # The name of the preset voice to use.
    string voiceName?;
};

# Grounding support.
public type GroundingSupport record {
    # Segment of the content this support belongs to.
    Segment segment?;
    # A list of indices (into 'grounding_chunk') specifying the
    #  citations associated with the claim. For instance [1,3,4] means
    #  that grounding_chunk[1], grounding_chunk[3],
    #  grounding_chunk[4] are the retrieved content attributed to the claim.
    int:Signed32[] groundingChunkIndices?;
    # Confidence score of the support references. Ranges from 0 to 1. 1 is the
    #  most confident. This list must have the same size as the
    #  grounding_chunk_indices.
    float[] confidenceScores?;
};

# Candidates with top log probabilities at each decoding step.
public type LogprobsResult_TopCandidates record {
    # Sorted by log probability in descending order.
    LogprobsResult_Candidate[] candidates?;
};

# GoogleSearch tool type.
#  Tool to support Google Search in Model. Powered by Google.
public type Tool_GoogleSearch record {
    # Optional. Filter search results to a specific time range.
    #  If customers set a start time, they must set an end time (and vice
    #  versa).
    Interval timeRangeFilter?;
};

# A predicted `FunctionCall` returned from the model that contains
#  a string representing the `FunctionDeclaration.name` with the
#  arguments and their values.
public type FunctionCall record {
    # Optional. The unique id of the function call. If populated, the client to
    #  execute the `function_call` and return the response with the matching `id`.
    string id?;
    # Required. The name of the function to call.
    #  Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum
    #  length of 63.
    string name;
    # Optional. The function parameters and values in JSON object format.
    record {} args?;
};

# Configuration for specifying function calling behavior.
public type FunctionCallingConfig record {
    # Optional. Specifies the mode in which function calling should execute. If
    #  unspecified, the default value will be set to AUTO.
    int mode?;
    # Optional. A set of function names that, when provided, limits the functions
    #  the model will call.
    # 
    #  This should only be set when the Mode is ANY. Function names
    #  should match [FunctionDeclaration.name]. With mode set to ANY, model will
    #  predict a function call from the set of function names provided.
    string[] allowedFunctionNames?;
};

# Config for thinking features.
public type ThinkingConfig record {
    # Indicates whether to include thoughts in the response.
    #  If true, thoughts are returned only when available.
    boolean includeThoughts?;
    # The number of thoughts tokens that the model should generate.
    int:Signed32 thinkingBudget?;
};

# Filter condition applicable to a single key.
public type Condition record {
    # The string value to filter the metadata on.
    string stringValue?;
    # The numeric value to filter the metadata on.
    float numericValue?;
    # Required. Operator applied to the given key-value pair to trigger the
    #  condition.
    int operation;
};

# A repeated list of passages.
public type GroundingPassages record {
    # List of passages.
    GroundingPassage[] passages?;
};

# A list of floats representing an embedding.
public type ContentEmbedding record {
    # The embedding values.
    float[] values;
};

# The result output from a `FunctionCall` that contains a string
#  representing the `FunctionDeclaration.name` and a structured JSON
#  object containing any output from the function is used as context to
#  the model. This should contain the result of a`FunctionCall` made
#  based on model prediction.
public type FunctionResponse record {
    # Optional. The id of the function call this response is for. Populated by
    #  the client to match the corresponding function call `id`.
    string id?;
    # Required. The name of the function to call.
    #  Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum
    #  length of 63.
    string name;
    # Required. The function response in JSON object format.
    record {} response;
    # Optional. Signals that function call continues, and more responses will be
    #  returned, turning the function call into a generator.
    #  Is only applicable to NON_BLOCKING function calls, is ignored otherwise.
    #  If set to false, future responses will not be considered.
    #  It is allowed to return empty `response` with `will_continue=False` to
    #  signal that the function call is finished. This may still trigger the model
    #  generation. To avoid triggering the generation and finish the function
    #  call, additionally set `scheduling` to `SILENT`.
    boolean willContinue?;
    # Optional. Specifies how the response should be scheduled in the
    #  conversation. Only applicable to NON_BLOCKING function calls, is ignored
    #  otherwise. Defaults to WHEN_IDLE.
    int scheduling?;
};

# Chunk from the web.
public type GroundingChunk_Web record {
    # URI reference of the chunk.
    string uri?;
    # Title of the chunk.
    string title?;
};

# The configuration for the multi-speaker setup.
public type MultiSpeakerVoiceConfig record {
    # Required. All the enabled speaker voices.
    SpeakerVoiceConfig[] speakerVoiceConfigs;
};

# Tool to retrieve public web data for grounding, powered by Google.
public type GoogleSearchRetrieval record {
    # Specifies the dynamic retrieval configuration for the given source.
    DynamicRetrievalConfig dynamicRetrievalConfig?;
};

# Safety rating for a piece of content.
# 
#  The safety rating contains the category of harm and the
#  harm probability level in that category for a piece of content.
#  Content is classified for safety across a number of
#  harm categories and the probability of the harm classification is included
#  here.
public type SafetyRating record {
    # Required. The category for this rating.
    int category;
    # Required. The probability of harm for this content.
    int probability;
    # Was this content blocked because of this rating?
    boolean blocked?;
};

# Passage included inline with a grounding configuration.
public type GroundingPassage record {
    # Identifier for the passage for attributing this passage in grounded
    #  answers.
    string id?;
    # Content of the passage.
    Content content?;
};

# User provided filter to limit retrieval based on `Chunk` or `Document` level
#  metadata values.
#  Example (genre = drama OR genre = action):
#    key = "document.custom_metadata.genre"
#    conditions = [{string_value = "drama", operation = EQUAL},
#                  {string_value = "action", operation = EQUAL}]
public type MetadataFilter record {
    # Required. The key of the metadata to filter on.
    string 'key;
    # Required. The `Condition`s for the given key that will trigger this filter.
    #  Multiple `Condition`s are joined by logical ORs.
    Condition[] conditions;
};

# Response from the model for a grounded answer.
public type GenerateAnswerResponse record {
    # Candidate answer from the model.
    # 
    #  Note: The model *always* attempts to provide a grounded answer, even when
    #  the answer is unlikely to be answerable from the given passages.
    #  In that case, a low-quality or ungrounded answer may be provided, along
    #  with a low `answerable_probability`.
    Candidate answer?;
    # Output only. The model's estimate of the probability that its answer is
    #  correct and grounded in the input passages.
    # 
    #  A low `answerable_probability` indicates that the answer might not be
    #  grounded in the sources.
    # 
    #  When `answerable_probability` is low, you may want to:
    # 
    #  * Display a message to the effect of "We couldn’t answer that question" to
    #  the user.
    #  * Fall back to a general-purpose LLM that answers the question from world
    #  knowledge. The threshold and nature of such fallbacks will depend on
    #  individual use cases. `0.5` is a good starting threshold.
    float answerableProbability?;
    # Output only. Feedback related to the input data used to answer the
    #  question, as opposed to the model-generated response to the question.
    # 
    #  The input data can be one or more of the following:
    # 
    #  - Question specified by the last entry in `GenerateAnswerRequest.content`
    #  - Conversation history specified by the other entries in
    #  `GenerateAnswerRequest.content`
    #  - Grounding sources (`GenerateAnswerRequest.semantic_retriever` or
    #  `GenerateAnswerRequest.inline_passages`)
    GenerateAnswerResponse_InputFeedback inputFeedback?;
};

# Request containing the `Content` for the model to embed.
public type EmbedContentRequest record {
    # Required. The model's resource name. This serves as an ID for the Model to
    #  use.
    # 
    #  This name should match a model name returned by the `ListModels` method.
    # 
    #  Format: `models/{model}`
    string model;
    # Required. The content to embed. Only the `parts.text` fields will be
    #  counted.
    Content content;
    # Optional. Optional task type for which the embeddings will be used. Not
    #  supported on earlier models (`models/embedding-001`).
    int taskType?;
    # Optional. An optional title for the text. Only applicable when TaskType is
    #  `RETRIEVAL_DOCUMENT`.
    # 
    #  Note: Specifying a `title` for `RETRIEVAL_DOCUMENT` provides better quality
    #  embeddings for retrieval.
    string title?;
    # Optional. Optional reduced dimension for the output embedding. If set,
    #  excessive values in the output embedding are truncated from the end.
    #  Supported by newer models since 2024 only. You cannot set this value if
    #  using the earlier model (`models/embedding-001`).
    int:Signed32 outputDimensionality?;
};

# Request to generate a grounded answer from the `Model`.
public type GenerateAnswerRequest record {
    # Passages provided inline with the request.
    GroundingPassages inlinePassages?;
    # Content retrieved from resources created via the Semantic Retriever
    #  API.
    SemanticRetrieverConfig semanticRetriever?;
    # Required. The name of the `Model` to use for generating the grounded
    #  response.
    # 
    #  Format: `model=models/{model}`.
    string model;
    # Required. The content of the current conversation with the `Model`. For
    #  single-turn queries, this is a single question to answer. For multi-turn
    #  queries, this is a repeated field that contains conversation history and
    #  the last `Content` in the list containing the question.
    # 
    #  Note: `GenerateAnswer` only supports queries in English.
    Content[] contents;
    # Required. Style in which answers should be returned.
    int answerStyle;
    # Optional. A list of unique `SafetySetting` instances for blocking unsafe
    #  content.
    # 
    #  This will be enforced on the `GenerateAnswerRequest.contents` and
    #  `GenerateAnswerResponse.candidate`. There should not be more than one
    #  setting for each `SafetyCategory` type. The API will block any contents and
    #  responses that fail to meet the thresholds set by these settings. This list
    #  overrides the default settings for each `SafetyCategory` specified in the
    #  safety_settings. If there is no `SafetySetting` for a given
    #  `SafetyCategory` provided in the list, the API will use the default safety
    #  setting for that category. Harm categories HARM_CATEGORY_HATE_SPEECH,
    #  HARM_CATEGORY_SEXUALLY_EXPLICIT, HARM_CATEGORY_DANGEROUS_CONTENT,
    #  HARM_CATEGORY_HARASSMENT are supported.
    #  Refer to the
    #  [guide](https://ai.google.dev/gemini-api/docs/safety-settings)
    #  for detailed information on available safety settings. Also refer to the
    #  [Safety guidance](https://ai.google.dev/gemini-api/docs/safety-guidance) to
    #  learn how to incorporate safety considerations in your AI applications.
    SafetySetting[] safetySettings?;
    # Optional. Controls the randomness of the output.
    # 
    #  Values can range from [0.0,1.0], inclusive. A value closer to 1.0 will
    #  produce responses that are more varied and creative, while a value closer
    #  to 0.0 will typically result in more straightforward responses from the
    #  model. A low temperature (~0.2) is usually recommended for
    #  Attributed-Question-Answering use cases.
    float temperature?;
};

# Metadata related to retrieval in the grounding flow.
public type RetrievalMetadata record {
    # Optional. Score indicating how likely information from google search could
    #  help answer the prompt. The score is in the range [0, 1], where 0 is the
    #  least likely and 1 is the most likely. This score is only populated when
    #  google search grounding and dynamic retrieval is enabled. It will be
    #  compared to the threshold to determine whether to trigger google search.
    float googleSearchDynamicRetrievalScore?;
};
